name: Deploy to Dokku

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decode SSH key and start ssh-agent
        run: |
          mkdir ~/.ssh
          echo "${{ vars.DOKKU_SSH_PRIVATE_KEY_BASE64 }}" | base64 --decode > ~/.ssh/id_ed25519

      - name: Add Dokku host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DOKKU_HOST }} >> ~/.ssh/known_hosts
          ssh -vvv dokku@${{ secrets.DOKKU_HOST }}
      - name: Deploy
        run: |
          git remote add dokku dokku@${{ secrets.DOKKU_HOST }}:${{ secrets.DOKKU_APP }} || true
          git push dokku main --force
